### ISSUE TITLE
Getting "callback function is not set"

### ISSUE THREAD

**Issue by drake0101** [sparky/perl-Net-Curl#16]
Hi,
Im getting "callback function is not set" if URL has a domain name. If I use IP the error doesnt show. I used a code example from http://stackoverflow.com/questions/36898569/understanding-async-in-perl-on-specific-example/ by Ikegami.
Ubuntu 14.04.4 LTS, 4.2.0-30-generic.
Net::Curl::Multi is up to date (0.37).
OS Curl removed and installed from source. C-ares also.
curl 7.48.0 (x86_64-pc-linux-gnu) libcurl/7.48.0 OpenSSL/1.0.1f zlib/1.2.8 c-ares/1.11.0 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

Any ideas what might couse this? ;)
Thanks!

**Comment by creaktive** [comment]
Not sure what causes that, but it appears to happen in this test, too: https://github.com/sparky/perl-Net-Curl/blob/master/t/60-multi-wait.t
Test is not failing in any obvious way.
