### ISSUE TITLE
Failed tests CURLSSLBACKEND_QSOSSL with perl 5.24

### ISSUE THREAD

**Issue by deemytch** [sparky/perl-Net-Curl#17]
Archlinux, x64, curl 7.49.1, perl 5.24
[net-curl-compiling.txt](https://github.com/sparky/perl-Net-Curl/files/318765/net-curl-compiling.txt)
[perl-v.txt](https://github.com/sparky/perl-Net-Curl/files/318764/perl-v.txt)

**Comment by creaktive** [comment]
Can you please check if this still happens with the new release (Net::Curl v0.38)?
