### ISSUE TITLE
make of Net-Curl-0.41.tar.gz failes - ‘CURLALTSVC_ALTUSED’ undeclared

### ISSUE THREAD

**Issue by anno73** [sparky/perl-Net-Curl#33]
During install of Net-Curl-0.41.tar.gz on a linux box recently I get following error:

Running Mkbootstrap for Curl ()
chmod 644 "Curl.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Curl.bs blib/arch/auto/Net/Curl/Curl.bs 644
"/usr/bin/perl" "/usr/share/perl/5.30/ExtUtils/xsubpp"  -typemap '/usr/share/perl/5.30/ExtUtils/typemap' -typemap '/root/.cpan/build/Net-Curl-0.41-2/typemap'  Curl.xs > Curl.xsc
mv Curl.xsc Curl.c
x86_64-linux-gnu-gcc -c   -Wall -Wno-unknown-pragmas  -O2 -g   -DVERSION=\"0.41\" -DXS_VERSION=\"0.41\" -fPIC "-I/usr/lib/x86_64-linux-gnu/perl/5.30/CORE"   Curl.c
In file included from Curl.xs:23:
./const-easy-xs.inc: In function ‘boot_Net__Curl’:
const-defenums-h.inc:2:29: error: ‘CURLALTSVC_ALTUSED’ undeclared (first use in this function)
    2 | # define CURLALTSVC_ALTUSED CURLALTSVC_ALTUSED
      |                             ^~~~~~~~~~~~~~~~~~
const-defenums-h.inc:2:29: note: in definition of macro ‘CURLALTSVC_ALTUSED’
    2 | # define CURLALTSVC_ALTUSED CURLALTSVC_ALTUSED
      |                             ^~~~~~~~~~~~~~~~~~
const-defenums-h.inc:2:29: note: each undeclared identifier is reported only once for each function it appears in
    2 | # define CURLALTSVC_ALTUSED CURLALTSVC_ALTUSED
      |                             ^~~~~~~~~~~~~~~~~~
const-defenums-h.inc:2:29: note: in definition of macro ‘CURLALTSVC_ALTUSED’
    2 | # define CURLALTSVC_ALTUSED CURLALTSVC_ALTUSED
      |                             ^~~~~~~~~~~~~~~~~~
make: *** [Makefile:360: Curl.o] Error 1
  SYP/Net-Curl-0.41.tar.gz
  /usr/bin/make -- NOT OK
Failed during this command:
 SYP/Net-Curl-0.41.tar.gz                     : make NO

Following cURL version is installed (debian package):

curl 7.66.0 (x86_64-pc-linux-gnu) libcurl/7.66.0 OpenSSL/1.1.1d zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.39.2 librtmp/2.3
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

Most likely this relates to latest changes (https://curl.haxx.se/changes.html - Fixed in 7.66.0 - September 11 2019):

Bugfixes:
CURLOPT_ALTSVC_CTRL.3: remove CURLALTSVC_ALTUSED

**Comment by eserte** [comment]
Already reported in https://github.com/sparky/perl-Net-Curl/issues/32

**Comment by eserte** [comment]
OK, #32 is a little bit different --- on debian it's a compilation failure, on freebsd & fedora it's just a test failure.
