### ISSUE TITLE
t/cleanup.t fails on freebsd 13

### ISSUE THREAD

**Issue by eserte** [sparky/perl-Net-Curl#37]
On my freebsd 13 smoker t/cleanup.t fails:
```
#   Failed test 'exception did not cause segfault'
#   at t/cleanup.t line 14.
#          got: '10'
#     expected: '10752'
# Looks like you failed 1 test of 1.
t/cleanup.t ................................ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
```
A full fail report:
http://www.cpantesters.org/cpan/report/1bfbc8a6-3daf-11ea-a4ca-ea331f24ea8f

There are no problems on my other freebsd systems (12, 11, 10, 9).

**Comment by FGasper** [comment]
It appears to be SIGBUS. (https://www.freebsd.org/cgi/man.cgi?query=signal&apropos=0&sektion=0&manpath=FreeBSD+12.1-RELEASE+and+Ports&arch=default&format=html)

Curiously, the test seems to fail sometimes with $? == 10 and other times with $? == 138, though I think the only difference is that 138 means a core dump happened. @eserte, is it possible to make that core dump available?

I created this test recently as part of the fix for the segfault issue I’d found. If it’s a problem I could make it skip outside author or release testing.

**Comment by FGasper** [comment]
I unfortunately don’t have access to a FreeBSD machine myself. It would be useful to know if the recent segfault fix is what produces the breakage here.

**Comment by eserte** [comment]
Here's a backtrace:
```
(gdb) bt
#0  0x0000000800bb481d in perl_curl_multi_magic_free () from /usr/home/cpansand/.cpan/build/2020020108/Net-Curl-0.43-0/blib/arch/auto/Net/Curl/Curl.so
#1  0x0000000000456200 in S_mg_free_struct ()
#2  0x00000000004561ab in Perl_mg_free ()
#3  0x000000000047f667 in Perl_sv_clear ()
#4  0x0000000000480331 in Perl_sv_free2 ()
#5  0x000000000047511f in Perl_sv_clean_objs ()
#6  0x00000000003da35a in perl_destruct ()
#7  0x00000000003bb3af in main ()
```
Is this helpful, or should I build a debugging perl for more information?

**Comment by FGasper** [comment]
I _think_ this is actually showing a different bug altogether. Will try to look later.

**Comment by FGasper** [comment]
I’ve got a VM up that shows this problem. The same failure happens if I bring this test in to v0.42, so at least v0.43 appears not to have regressed.

**Comment by FGasper** [comment]
I think I found the problem. The XS multi struct’s “easies” list isn’t updated as part of the cleanup of the easy. So when multi is cleaned up it tries to access already-freed stuff.

PR forthcoming.

**Comment by FGasper** [comment]
@eserte I think this is resolved in the latest dev builds; can you please confirm?

**Comment by creaktive** [comment]
All FreeBSD versions are passing now, therefore I'm closing this ticket: https://www.cpantesters.org/distro/N/Net-Curl.html?oncpan=1&distmat=1&version=0.44_3&grade=3
