### ISSUE TITLE
multi object lacks CURLMOPT_SOCKETFUNCTION callback!

### ISSUE THREAD

**Issue by eserte** [sparky/perl-Net-Curl#49]
Calling examples/02-multi-simple.pl generates two warnings:
```
multi object lacks CURLMOPT_SOCKETFUNCTION callback! at examples/02-multi-simple.pl line 62.
multi object lacks CURLMOPT_SOCKETFUNCTION callback! at examples/02-multi-simple.pl line 62.
```
Probably this started with Net::Curl 0.44. Other than the warnings the script seems to work.

So what can be done to avoid this warning? Should the script call something like
```
$multi->setopt( Net::Curl::Multi::CURLMOPT_SOCKETFUNCTION, sub { return 1 });
```
Or shouldn't there be a warning at all in this situation?

**Comment by FGasper** [comment]
@eserte I added that warning with the understanding that proper use of the multi interface requires a socket callback, but I appear to have been mistaken.

I’ll submit a PR to remove that warning. Sorry!

**Comment by creaktive** [comment]
Thanks! Fix being tested :) http://matrix.cpantesters.org/?dist=Net-Curl+0.46_1

**Comment by eserte** [comment]
@FGasper: in 0.46 the warnings are still there, only the text changed. Calling examples/02-multi-simple.pl now outputs:
```
callback function is not set
callback function is not set
```

**Comment by FGasper** [comment]
@eserte That warning is almost 10 years old. I don’t see it when I run that script on master.

Do you see it in 0.42?

**Comment by eserte** [comment]
Actually I don't see it on every run with 0.46 (or master). Maybe it depends on timing --- if I prepend `strace -f -o/tmp/s.log` (which possibly slows down execution a little bit) I see it almost on every run.

And yes, it may happen also with v0.42 (built from git).
