### ISSUE TITLE
curl_slist_append using

### ISSUE THREAD

**Issue by cyrillpetroff** [sparky/perl-Net-Curl#73]
Hello. Apparently, there is some kind of error in the module. I use `$easy->pushopt(CURLOPT_PROXYHEADER, ['a: b']);` and get `Unknown error`. I rewrote this code in python, everything works fine there.

**Comment by noxxi** [comment]
Looks like CURLOPT_PROXYHEADER wasn't treated the same as CURLOPT_HTTPHEADER in that it is a list. The following patch fixes this for me:

```
--- a/Curl_Easy.xsh
+++ b/Curl_Easy.xsh
@@ -29,6 +29,7 @@ typedef enum {
 
 static const CURLoption perl_curl_easy_option_slist[] = {
        CURLOPT_HTTPHEADER,
+       CURLOPT_PROXYHEADER,
        CURLOPT_HTTP200ALIASES,
 #ifdef CURLOPT_MAIL_RCPT
        CURLOPT_MAIL_RCPT,
```

**Comment by creaktive** [comment]
Thanks, @cyrillpetroff & @noxxi! Fix pushed; if it works for you guys I'll release Net::Curl to CPAN later this week.

**Comment by noxxi** [comment]
> Thanks, @cyrillpetroff & @noxxi! Fix pushed; if it works for you guys I'll release Net::Curl to CPAN later this week.

Works fine for me. Thanks for the quick fix.

**Comment by creaktive** [comment]
Released to CPAN: https://metacpan.org/release/SYP/Net-Curl-0.54
