### ISSUE TITLE
t/old-10errbuf.t may fail (curl 7.64.0)

### ISSUE THREAD

**Issue by eserte** [sparky/perl-Net-Curl#75]
In rare situations t/old-10errbuf.t may fail like this:

```
#   Failed test 'Non-zero return code indicates the expected failure'
#   at t/old-10errbuf.t line 41.

#   Failed test 'Reading redirected STDERR'
#   at t/old-10errbuf.t line 50.
#                   '*   Trying 12.34.56.78...'
#     doesn't match '(?^ix:^\*\s+(?:
#     Protocol \s "? badprotocol "? \s not \s supported \s or \s disabled \s in \s libcurl |
#     Unsupported \s protocol: \s badprotocol |
#     Rebuilt \s URL \s to: \s badprotocol://.+ |
#     Closing \s connection \s -1 |
#     Could \s not \s resolve \s host: \s badprotocol |
#     Could \s not \s resolve: \s badprotocol \(Domain \s name \s not \s found\) |
#     Expire \s in \s 0 \s ms \s for \s 6 \s \(transfer \s 0x[0-9a-f]+\) |
#     Uses \s proxy \s env \s variable \s https?_proxy \s == \s '[^']+'
# )$)'
# Looks like you failed 2 tests of 13.
t/old-10errbuf.t ........................... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/13 subtests 
```

It seems that curl versions exist which interpret "badprotocol" as host name (for example 7.64.0, which can be found in debian:buster). This can be reproduced like this:

```
$ docker run -it debian:buster sh -c 'apt update -q && apt install curl -qy && curl badprotocol://127.0.0.1:2'
...
curl: (6) Could not resolve host: badprotocol
```

If the local DNS is able to resolve "badprotocol", either because such a host really exist, or because wildcard DNS records are active, and there's a webserver listening on such a host, then the curl call is successful and the test fails.

This explains at least three fail reports from my smokers (for example http://www.cpantesters.org/cpan/report/eac3cc1e-a670-11ee-a77b-9a3d6e8775ea )

**Comment by eserte** [comment]
If wildcard DNS records active, then a workaround is to set something like `export LOCALDOMAIN=example.org` before running the tests.

**Comment by creaktive** [comment]
Thanks for looking into this, @eserte! And thanks a lot for your smokers :)
It looks like `badprotocol://127.0.0.1:2` doesn't make a great invalid URL, after all. With some experimentation (in which your smokers played a crucial role), I found an option that fails in more predictable ways: `http://0.0.0.0:123456`. Adjusted `t/old-10errbuf.t` accordingly and it is much cleaner now.
